# CAU 1
SELECT IDINVOICE, SUM(AMOUNT)
FROM DETAILINVOICE
GROUP BY IDINVOICE

# CAU 2
SELECT IDINVOICE, SUM(DI.AMOUNT * B.PRICE) AS TONGGIA
FROM DETAILINVOICE DI
JOIN BOOK B ON B.IDBOOK = DI.IDBOOK
GROUP BY IDINVOICE

# CAU 3
SELECT IDINVOICE, SUM(DI.AMOUNT * B.PRICE) AS TONGGIA
FROM DETAILINVOICE DI
JOIN BOOK B ON B.IDBOOK = DI.IDBOOK
JOIN CATEGORY C ON B.IDCATEGORY = C.IDCATEGORY
WHERE C.NAME IN ('Khoa học', 'Văn học')
GROUP BY IDINVOICE

# CAU 4
SELECT B.TITLE, SUM(DI.AMOUNT) AS TONGSOLUONG
FROM DETAILINVOICE DI
JOIN INVOICE I ON I.IDINVOICE = DI.IDINVOICE
JOIN BOOK B ON B.IDBOOK = DI.IDBOOK
# WHERE I.CREATEDATE BETWEEN '2021-01-01' AND '2021-12-31'
# WHERE '2021-01-01' <= I.CREATEDATE <= '2021-12-31'
WHERE YEAR(I.CREATEDATE) = '2021'
GROUP BY B.IDBOOK, B.TITLE
ORDER BY SUM(DI.AMOUNT) DESC
LIMIT 1

# CAU 5
UPDATE INVOICE I
JOIN (
  SELECT DI.IDINVOICE, SUM(DI.AMOUNT * B.PRICE) AS TONGGIA
  FROM DETAILINVOICE DI
  JOIN BOOK B ON B.IDBOOK = DI.IDBOOK
  GROUP BY DI.IDINVOICE
 ) SQ ON I.IDINVOICE = SQ.IDINVOICE
SET TOTAL = TONGGIA
